# Generated by Django 5.2.14 on 2026-05-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle Database'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL / MariaDB'), ('sqlite', 'SQLite'), ('excel', 'Excel Workbook'), ('csv', 'CSV / Text File')], max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('test_status', models.CharField(choices=[('untested', 'Untested'), ('ok', 'Connected'), ('failed', 'Failed')], default='untested', max_length=10)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_data_sources', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='accounts.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
