# Generated by Django 5.2.14 on 2026-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle Database'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL / MariaDB'), ('sqlite', 'SQLite'), ('odbc', 'Generic ODBC / DSN'), ('excel', 'Excel Workbook'), ('csv', 'CSV / Text File')], max_length=20),
        ),
    ]
