# Generated by Django 5.2.14 on 2026-05-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='datasets.dataset'),
        ),
    ]
