# Generated by Django 5.2.14 on 2026-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_dashboardsharetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('bar', 'Bar chart'), ('line', 'Line chart'), ('pie', 'Pie chart'), ('area', 'Area chart'), ('scatter', 'Scatter plot'), ('histogram', 'Histogram'), ('heatmap', 'Heatmap'), ('boxplot', 'Box plot'), ('kpi', 'KPI card'), ('table', 'Table'), ('text', 'Text / Note')], default='bar', max_length=12),
        ),
    ]
