# Generated by Django 5.2.14 on 2026-06-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_queryrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(max_length=128)),
                ('key_columns', models.JSONField(blank=True, default=list)),
                ('watermark_column', models.CharField(blank=True, max_length=128)),
                ('high_watermark', models.CharField(blank=True, max_length=64)),
                ('cadence', models.CharField(choices=[('hourly', 'Hourly (incremental)'), ('daily', 'Daily (incremental)'), ('weekly', 'Weekly (full)')], default='hourly', max_length=10)),
                ('last_full_at', models.DateTimeField(blank=True, null=True)),
                ('last_incremental_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_sources', to='connections.datasource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_targets', to='connections.datasource')),
            ],
            options={
                'ordering': ['table_name'],
                'unique_together': {('source', 'target', 'table_name')},
            },
        ),
    ]
