# Generated by Django 5.2.14 on 2026-06-17 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0007_alter_alertevent_id_alter_datasetalert_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('workflow', models.CharField(choices=[('anomaly', 'Anomaly detection'), ('statistics', 'Statistical test'), ('forecast', 'Forecast')], max_length=20)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'workflow', '-created_at'], name='analytics_a_owner_i_445044_idx'), models.Index(fields=['dataset', 'workflow'], name='analytics_a_dataset_a0d8f9_idx'), models.Index(fields=['status'], name='analytics_a_status_463e2e_idx')],
            },
        ),
    ]
