# Generated by Django 5.2.14 on 2026-05-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('database', models.CharField(blank=True, help_text='Optional target database override.', max_length=255)),
                ('mode', models.CharField(choices=[('builder', 'Visual Builder'), ('raw', 'Raw SQL')], default='builder', max_length=10)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('raw_sql', models.TextField(blank=True)),
                ('generated_sql', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.IntegerField(blank=True, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='connections.datasource')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_queries', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='accounts.site')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
