# Generated by Django 5.2.14 on 2026-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lab_manager', 'Laboratory Manager'), ('qa_manager', 'QA / QC Manager'), ('section_head', 'Section Head'), ('senior_analyst', 'Senior Analyst'), ('analyst', 'Analyst / Chemist'), ('qc_chemist', 'QC Chemist'), ('lab_technician', 'Lab Technician'), ('sample_custodian', 'Sample Custodian'), ('instrument_engineer', 'Instrument & Calibration Engineer'), ('viewer', 'Viewer / Client')], default='viewer', max_length=32),
        ),
    ]
