# Generated by Django 5.2.14 on 2026-06-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_queryrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_table', models.CharField(max_length=128)),
                ('right_table', models.CharField(max_length=128)),
                ('on', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certified_joins', to='connections.datasource')),
            ],
            options={
                'ordering': ['left_table', 'right_table'],
            },
        ),
        migrations.CreateModel(
            name='SemanticLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_layer', to='connections.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('in_scope', models.BooleanField(default=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_tables', to='connections.datasource')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('datasource', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CertifiedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sql', models.TextField()),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certified_metrics', to='connections.datasource')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('datasource', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SemanticColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('dtype', models.CharField(blank=True, max_length=64)),
                ('encoding', models.CharField(blank=True, max_length=255)),
                ('null_fraction', models.FloatField(blank=True, null=True)),
                ('needs_cast', models.BooleanField(default=False)),
                ('do_not_group', models.BooleanField(default=False)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='semantics.semantictable')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('table', 'name')},
            },
        ),
    ]
