# Generated by Django 5.2.14 on 2026-06-03 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0007_alter_alertevent_id_alter_datasetalert_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('document', 'Uploaded document'), ('dataset', 'Dataset rows')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate (auto-flagged)')], db_index=True, default='pending', max_length=16)),
                ('doc_id', models.CharField(max_length=512)),
                ('passages', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_file', models.CharField(blank=True, max_length=512)),
                ('ingest_options', models.JSONField(blank=True, default=dict)),
                ('passage_count', models.IntegerField(default=0)),
                ('token_estimate', models.IntegerField(default=0)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_records_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_records', to='datasets.dataset')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='docsearch.knowledgerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_records_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'source_type'], name='docsearch_k_status_bdb35c_idx'), models.Index(fields=['content_hash'], name='docsearch_k_content_99d722_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('content_hash',), name='uniq_approved_content_hash')],
            },
        ),
    ]
